[project]
org-name= "gayal"
version= "0.1.0"

[platform]
target = "java11"

    [[platform.libraries]]
    artafactId = "ojdbc8"
    # version = "8"
    path = "/usr/share/java/OJDBC8-Full/ojdbc8.jar"
    # groupId = "com.h2database"
    modules = ["validation"]

    [[platform.libraries]]
    artifactId = "orai18n"
    # version = "3.3.1"
    path = "/usr/share/java/OJDBC8-Full/orai18n.jar"
    # groupId = "com.zaxxer"
    modules = ["validation"]

[build-options]
observability-included=true

[dependencies]
